-- VIEW 

CREATE VIEW StuView AS 
SELECT S.STUDENT_ID AS "ID", S.S_FNAME ||' '||S.S_LName AS "STUDENT", A.REG_CREDITS AS "REGISTERED CREDITS ", A.EARNED_HOURS AS "EARNED HOURS", 
A.CGPA AS "CGPA",CURRENT_STATUS AS "STATUS", F.F_FNAME ||' '|| F.F_LNAME AS "ADVISOR", S.S_College AS "COLLEGE ID"
FROM Student S, ACADAMIC_RECORD A, FACULTY F
WHERE S.S_Advisor = Faculty_ID AND S.STUDENT_ID = A.STUDENT_ID
ORDER BY CURRENT_STATUS desc;